### ISSUE TITLE
Add optional transform objects to topology object

### ISSUE THREAD

**Issue by patricoferris** [geocaml/ocaml-topojson#14]
We currently don't support the optional transform object which is a part of the topology object. See this part of the specification https://github.com/topojson/topojson-specification#212-transforms which details:

> A topology may have a “transform” member whose value is a transform object. The purpose of the transform is to quantize positions for more efficient serialization, by representing positions as integers rather than floats.

https://github.com/geocaml/ocaml-topojson/blob/5bc10d52c1102e5a4a666848e17d45768a70669d/src/topojson/topojson.ml#L379-L383

**Comment by mariamadronah** [comment]
Hello @patricoferris , I am Mariam an outreachy applicant from uganda and would love to contribute through this issue since I already set up ocaml and everything necessary. Please assign it to me and provide any necessary details to help solve this issue. Thank you.

**Comment by patricoferris** [comment]
Hi @mariamadronah, how's everything going, are you stuck or need any help ?

**Comment by mariamadronah** [comment]
hello @patricoferris , thank you for asking. So I have gone through the documentations of topojson and understood the different objects including the basics OCaml so as to understand options, pattern matching and the sort but am stuck trying to understand how arcs, objects' implementation was made in the code so as I replicate the same to transform objects especially since arcs and transform have some similarity , probably I be helped there.

**Comment by Priceless-P** [comment]
Hi @patricoferris, Can I work on this next?

**Comment by patricoferris** [comment]
Yes please ^^

**Comment by patricoferris** [comment]
Fixed in #32
